

import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <Link href="/user">Go to User Page</Link> <br/> <br/>
      <Link href="/products">Go to Products Page</Link>
        {children}
      </body>
    </html>
  );
}
