


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <a href ="/admin">Admin</a> <br/><br/>
            <a href ="/user">User</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
